### PR TITLE
Add purge schema

### PR DESCRIPTION
**Pull request by BWStearns**

### CODE REVIEW

**Comment by BWStearns** [comment]
Changes to comments in unmodified code were made to satisfy new Flake8 requirements.

**Comment by BWStearns** [comment]
The comment changes were because flake8 was yelling at me about imperative voice.

**Comment by lbedner** [comment]
@BWStearns Should these changes be added to the [Changelog](https://github.com/iheartradio/pipeline/blob/master/docs/changes.rst)?

**Comment by BWStearns** [comment]
@lbedner probably. Will do now.

**Pull request merged**
